cask "vlc"

cask "github"
cask "transmit"
cask "sublime-text"
cask "sequel-ace"
cask "tableplus"

cask "font-lato"
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro-for-powerline"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "font-hack-nerd-font"