[".dotfiles/zsh/ohmyzsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".dotfiles/zsh/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".dotfiles/tmux/plugins/tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux"
[".dotfiles/vim/plugins/Vundle.vim"]
	type = "git-repo"
	url = "https://github.com/gmarik/Vundle.vim.git"
[".dotfiles/zsh/custom/plugins/fzf-tab"]
	type = "git-repo"
	url = "https://github.com/Aloxaf/fzf-tab"
[".dotfiles/zsh/custom/plugins/zsh-autosuggestions"]
	type = "git-repo"
	url = "https://github.com/zsh-users/zsh-autosuggestions/"
