#!/usr/executable_bin/env zsh
# Make alias


	if [ "$1" != "" ]
	then
		if [ "$2" != "" ]
			
		then
			echo "alias $1=$2" >> ~/.zprofile && source ~/.zprofile
		else
			echo "alias $1=\"$(fc -ln -1)\"" >> ~/.zprofile && source ~/.zprofile 
		fi
	else
		echo "??"
	fi
