name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      REMOTE_CONTAINERS: "True"
    strategy:
      fail-fast: false
      matrix:
        variant: [devcontainer, wsl, gnome]
        os: [ubuntu-20.04, ubuntu-22.04]
        include:
#       TODO: Add alpine and arch supports
#          - variant: devcontainer
#            os: alpine
          - variant: devcontainer
            os: debian
          - os: macos-11
            variant: darwin
          - os: macos-12
            variant: darwin
          - os: macos-13
            variant: darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          scripts/test.sh --variant "${{ matrix.variant }}" --os "${{ matrix.os }}"